// SPDX-License-Identifier: MIT
pragma solidity >=0.8.0;

/* Autogenerated file. Do not edit manually. */
enum MonsterCatchResult {
  Missed,
  Caught,
  Fled
}

enum MonsterType {
  None,
  Eagle,
  Rat,
  Caterpillar
}

enum TerrainType {
  None,
  Question,
  Tree,
  Trigger,
  Bomb
}

enum QuestionType {
  None,
  One,
  Two,
  Three,
  Four,
  Five,
  Six,
  Seven,
  Eight,
  Nine,
  Ten
}
